import type { QuizQuestion } from './types.js';

// The 15-question bank. Each option carries the prediction weights:
//  - sections: points toward the 10 topology sections (outcome intents)
//  - types:    points toward the 6 profile types
//  - tags:     +4 per keyword hit in a career item's text
//  - avoid:    -8 per keyword hit
//  - signal / constraint: fills the client's dashboard models
export const QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    text: 'Easy one first. A whole workday on your feet moving between people and places, or at a desk with your setup just right?',
    probe: 'whole workday on your feet',
    options: [
      {
        label: 'On my feet, moving',
        react: 'Same energy as every great ward nurse I know.',
        reflect: 'you want a job you can feel in your legs, not just your laptop',
        sections: { frontlineJobs: 3, government: 1 },
        types: { operator: 2 },
        tags: ['ward', 'clinical', 'theatre', 'emergency', 'hospital', 'bedside', 'field'],
      },
      {
        label: 'At a desk, focused',
        react: 'A deep-focus person. Noted.',
        reflect: 'you do your best work in quiet, focused stretches',
        sections: { research: 2, industryRoles: 2 },
        types: { investigator: 2 },
        tags: ['data', 'analysis', 'research', 'documentation', 'informatics', 'coding', 'writing', 'quality'],
      },
      {
        label: 'Honestly, a mix',
        react: 'Flexible. That opens a lot of doors.',
        reflect: 'you like switching between field and desk instead of living in one',
        sections: { frontlineJobs: 1, industryRoles: 1 },
        types: { strategist: 1 },
        tags: ['coordinator', 'manager', 'liaison', 'consultant'],
      },
    ],
  },
  {
    id: 'q2',
    text: 'A full day of people — patients, families, teammates, nonstop. Does that fill your battery or drain it?',
    probe: 'fill your battery or drain it',
    options: [
      {
        label: 'Fills it, I love people',
        react: 'People-people are rarer than they think.',
        reflect: 'being around people genuinely charges you',
        sections: { frontlineJobs: 2, civilServices: 1 },
        types: { connector: 2 },
        tags: ['patient', 'care', 'counsel', 'community', 'education', 'family', 'outreach'],
        signal: { key: 'extraversion', value: 'high', label: 'People-energized', description: 'Draws energy from interaction; suits patient-facing and team roles.' },
      },
      {
        label: 'Drains me, honestly',
        react: 'Respect the honesty. Quiet depth is a superpower too.',
        reflect: 'you recharge alone and go deepest in quiet work',
        sections: { research: 2, industryRoles: 1 },
        types: { investigator: 2 },
        tags: ['laboratory', 'lab', 'data', 'analysis', 'molecular', 'microscopy', 'informatics'],
        avoid: ['counsel'],
        signal: { key: 'extraversion', value: 'low', label: 'Depth over crowds', description: 'Recharges solo; suits lab, data and research environments.' },
      },
      {
        label: 'Depends on the people',
        react: 'Fair. Chemistry matters.',
        reflect: 'the right team matters more to you than the size of the crowd',
        sections: { industryRoles: 1 },
        types: { connector: 1 },
        signal: { key: 'extraversion', value: 'medium', label: 'Selectively social', description: 'Works well in small, trusted teams.' },
      },
    ],
  },
  {
    id: 'q3',
    text: 'Alarms going off, a real emergency right in front of you. What happens inside you?',
    probe: 'real emergency right in front of you',
    options: [
      {
        label: 'I switch on. Total focus.',
        react: 'That calm-in-chaos thing cannot be taught.',
        reflect: 'pressure switches you on instead of shutting you down',
        sections: { frontlineJobs: 3 },
        types: { operator: 2 },
        tags: ['emergency', 'trauma', 'icu', 'critical', 'acute', 'resuscitation', 'operation'],
        signal: { key: 'stability', value: 'high', label: 'Calm under fire', description: 'Performs best in acute, high-stakes moments.' },
      },
      {
        label: "I'd rather build systems so it never happens",
        react: 'The quiet architect. Hospitals run on people like you.',
        reflect: 'you prefer preventing fires over fighting them',
        sections: { research: 1, industryRoles: 1, government: 1 },
        types: { strategist: 1, investigator: 1 },
        tags: ['quality', 'safety', 'prevention', 'audit', 'planning', 'surveillance', 'policy'],
        signal: { key: 'stability', value: 'planner', label: 'Prevention-minded', description: 'Steady, methodical; suits quality, safety and planning roles.' },
      },
      {
        label: 'Panic first, then I steady',
        react: 'More honest than half the doctors I know.',
        reflect: 'you need a beat to settle, then you deliver',
        sections: { industryRoles: 1, certifications: 1 },
        signal: { key: 'stability', value: 'medium', label: 'Settles under structure', description: 'Thrives with protocols and preparation.' },
      },
    ],
  },
  {
    id: 'q4',
    text: 'Pick your favourite work companion: machines and instruments, people and patients, or data and patterns?',
    probe: 'favourite work companion',
    options: [
      {
        label: 'Machines & instruments',
        react: 'A hands-on-hardware person.',
        reflect: 'you like tools and tech you can actually touch',
        sections: { frontlineJobs: 1, industryRoles: 1, emerging: 1 },
        types: { builder: 2 },
        tags: ['equipment', 'device', 'imaging', 'instrument', 'technology', 'machine', 'scanner', 'robotic'],
      },
      {
        label: 'People & patients',
        react: 'Care work chooses its people. It may have chosen you.',
        reflect: 'the human side of healthcare is what pulls you',
        sections: { frontlineJobs: 2 },
        types: { connector: 2 },
        tags: ['patient', 'care', 'therapy', 'rehabilitation', 'counsel', 'nursing', 'clinical'],
      },
      {
        label: 'Data & patterns',
        react: 'Pattern-spotters end up running the show quietly.',
        reflect: 'you see the story hiding inside numbers',
        sections: { research: 2, industryRoles: 1 },
        types: { investigator: 2 },
        tags: ['data', 'bioinformatics', 'statistics', 'analysis', 'genomics', 'epidemiology', 'informatics', 'ai'],
      },
    ],
  },
  {
    id: 'q5',
    text: 'Group project. Which one is you, really?',
    probe: 'Group project. Which one is you',
    options: [
      {
        label: 'I end up leading it',
        react: 'Born supervisor energy.',
        reflect: 'you naturally end up steering the group',
        sections: { government: 1, industryRoles: 1, civilServices: 1 },
        types: { strategist: 2 },
        tags: ['manager', 'supervisor', 'lead', 'director', 'head', 'administrator', 'officer'],
        signal: { key: 'agreeableness', value: 'leader', label: 'Takes charge', description: 'Comfortable owning decisions and directing work.' },
      },
      {
        label: 'I quietly do the hardest part',
        react: 'The one who actually makes it happen.',
        reflect: 'you let your work speak while others talk',
        sections: { frontlineJobs: 2, certifications: 1 },
        types: { operator: 2 },
        tags: ['specialist', 'technician', 'technologist', 'analyst', 'expert'],
        signal: { key: 'agreeableness', value: 'doer', label: 'Quiet executor', description: 'Delivers the critical work without needing the spotlight.' },
      },
      {
        label: "I'm the ideas person",
        react: 'Every breakthrough starts with your type.',
        reflect: 'you generate the ideas others build on',
        sections: { emerging: 2, entrepreneurship: 1, research: 1 },
        types: { creator: 2 },
        tags: ['innovation', 'design', 'novel', 'development', 'emerging'],
        signal: { key: 'agreeableness', value: 'ideator', label: 'Idea engine', description: 'Original thinking; energized by what does not exist yet.' },
      },
      {
        label: 'I keep everyone together',
        react: 'The glue. Teams fall apart without you.',
        reflect: 'you hold teams together when things wobble',
        sections: { frontlineJobs: 1, government: 1 },
        types: { connector: 2 },
        tags: ['coordinator', 'liaison', 'community', 'team', 'training'],
        signal: { key: 'agreeableness', value: 'glue', label: 'Team glue', description: 'Builds trust and keeps groups functioning.' },
      },
    ],
  },
  {
    id: 'q6',
    text: 'Would you rather master one routine until you are flawless at it, or face something new every single day?',
    probe: 'master one routine until you are flawless',
    options: [
      {
        label: 'Mastery of a craft',
        react: 'Craftspeople age like gold in healthcare.',
        reflect: 'you would rather be excellent at one thing than average at ten',
        sections: { frontlineJobs: 2, certifications: 2 },
        types: { operator: 2 },
        tags: ['specialist', 'certified', 'technique', 'procedure', 'skill'],
      },
      {
        label: 'New challenge daily',
        react: 'A novelty engine. You would suffocate in routine.',
        reflect: 'sameness bores you fast, novelty keeps you alive',
        sections: { emerging: 2, entrepreneurship: 1 },
        types: { creator: 2 },
        tags: ['emerging', 'innovation', 'startup', 'dynamic', 'frontier', 'novel'],
      },
      {
        label: 'Stable base, some variety',
        react: 'Structured variety. Very sane.',
        reflect: 'you want a stable core with room to explore',
        sections: { government: 1, industryRoles: 1 },
        types: { strategist: 1 },
      },
    ],
  },
  {
    id: 'q7',
    text: 'When you look at anything — a form, a room, a plan — what do you notice first: the tiny details or the big picture?',
    probe: 'tiny details or the big picture',
    options: [
      {
        label: 'Tiny details',
        react: 'Detail-eyes save lives in this industry. Literally.',
        reflect: 'small errors jump out at you before anyone else sees them',
        sections: { frontlineJobs: 1, research: 1, certifications: 1 },
        types: { operator: 1, investigator: 1 },
        tags: ['quality', 'precision', 'audit', 'laboratory', 'documentation', 'compliance', 'dosimetry'],
        signal: { key: 'conscientiousness', value: 'high', label: 'Precision-first', description: 'Catches what others miss; suits QA, lab and compliance work.' },
      },
      {
        label: 'Big picture',
        react: 'Zoom-out brains end up making the big calls.',
        reflect: 'you think in systems and directions, not checklists',
        sections: { government: 1, industryRoles: 1, civilServices: 1, entrepreneurship: 1 },
        types: { strategist: 2 },
        tags: ['strategy', 'policy', 'management', 'planning', 'program', 'administration'],
        signal: { key: 'conscientiousness', value: 'strategic', label: 'Systems thinker', description: 'Sees the whole board; suits management and policy tracks.' },
      },
      {
        label: 'Both, depends on the day',
        react: 'Switch-hitter. Useful.',
        reflect: 'you can zoom in or out depending on what the moment needs',
        signal: { key: 'conscientiousness', value: 'balanced', label: 'Adaptive focus', description: 'Flexes between detail and overview.' },
      },
    ],
  },
  {
    id: 'q8',
    text: 'Someone asks you to explain something you know well. Do you secretly enjoy that moment?',
    probe: 'explain something you know well',
    options: [
      {
        label: 'Love it. I explain things all the time',
        react: 'Teacher energy. It always finds a way out.',
        reflect: 'explaining things gives you a quiet high',
        sections: { research: 1, frontlineJobs: 1 },
        types: { connector: 1 },
        tags: ['training', 'education', 'faculty', 'teaching', 'academic', 'mentor', 'tutor', 'communication'],
      },
      {
        label: 'Not really my thing',
        react: 'Noted. Doing over explaining.',
        reflect: 'you would rather do the thing than explain the thing',
        sections: { frontlineJobs: 1 },
        avoid: ['teaching', 'faculty'],
      },
      {
        label: 'To the right audience, yes',
        react: 'Selective broadcaster. Fair.',
        reflect: 'you enjoy sharing knowledge when it actually lands',
        tags: ['communication', 'liaison'],
      },
    ],
  },
  {
    id: 'q9',
    text: 'A stable government job — fixed hours, pension, security. Gut reaction: dream or boring?',
    probe: 'fixed hours, pension, security',
    options: [
      {
        label: 'Dream, honestly',
        react: 'Zero shame in wanting stability. It buys freedom.',
        reflect: 'security is not boring to you, it is the foundation',
        sections: { government: 3, civilServices: 2 },
        tags: ['government', 'public', 'national', 'railway', 'defence', 'municipal', 'state'],
        signal: { key: 'motivation', value: 'security', label: 'Stability-driven', description: 'Values security and structure; suits government and institutional tracks.' },
      },
      {
        label: 'Boring. I want more upside',
        react: 'Upside-hunter. The private side will suit you.',
        reflect: 'you would trade safety for a shot at something bigger',
        sections: { industryRoles: 2, entrepreneurship: 2 },
        types: { builder: 1 },
        tags: ['corporate', 'startup', 'industry', 'consulting', 'private'],
        signal: { key: 'motivation', value: 'growth', label: 'Upside-driven', description: 'Motivated by growth and ownership over security.' },
      },
      {
        label: 'Depends what the job is',
        react: 'Pragmatist. Respect.',
        reflect: 'you judge the work itself, not the label on it',
        sections: { government: 1, industryRoles: 1 },
        signal: { key: 'motivation', value: 'balanced', label: 'Role over label', description: 'Weighs each opportunity on its own merits.' },
      },
    ],
  },
  {
    id: 'q10',
    text: 'Ten years from now: your own clinic, lab or startup with your name on it. Does that picture excite you?',
    probe: 'your name on it',
    options: [
      {
        label: 'Yes. I want to build my own thing',
        react: 'Founder gene detected.',
        reflect: 'part of you is already building something of your own',
        sections: { entrepreneurship: 3, emerging: 1 },
        types: { builder: 2, creator: 1 },
        tags: ['startup', 'venture', 'founder', 'clinic', 'consultancy', 'agency', 'launching', 'own'],
      },
      {
        label: 'Too risky for me',
        react: 'Self-knowledge beats bravado.',
        reflect: 'you want a solid institution behind you, not a gamble',
        sections: { frontlineJobs: 1, government: 1 },
        avoid: ['startup', 'venture', 'founder'],
      },
      {
        label: 'Maybe, after I learn on the job',
        react: 'Earn, learn, then leap. Classic smart route.',
        reflect: 'you want experience first, ownership later',
        sections: { entrepreneurship: 1, industryRoles: 1, certifications: 1 },
        types: { builder: 1 },
      },
    ],
  },
  {
    id: 'q11',
    text: 'Real talk: 2-3 more years of studying after this degree. Exciting or exhausting?',
    probe: '2-3 more years of studying',
    options: [
      {
        label: 'Exciting. I actually love studying',
        react: 'The M.Sc.-and-beyond lane is wide open for you.',
        reflect: 'more study is not a cost to you, it is the fun part',
        sections: { pgPathways: 3, research: 2 },
        types: { investigator: 1 },
        tags: ['m.sc', 'phd', 'fellowship', 'msc', 'postgraduate', 'academic'],
        signal: { key: 'competence', value: 'scholar', label: 'Loves depth', description: 'Energy for advanced study and specialization.' },
      },
      {
        label: 'Exhausting. I want to work ASAP',
        react: 'Straight to the field. There is a fast lane for that.',
        reflect: 'you are done with classrooms and ready for the real thing',
        sections: { frontlineJobs: 3, certifications: 2 },
        avoid: ['phd'],
        signal: { key: 'competence', value: 'practitioner', label: 'Learn by doing', description: 'Builds skill fastest on the job.' },
      },
      {
        label: 'Only if it clearly pays off',
        react: 'ROI brain. Short courses and certs will love you.',
        reflect: 'you will invest in study only when the payoff is obvious',
        sections: { certifications: 3, globalPathways: 1 },
        tags: ['certification', 'certified', 'diploma', 'license'],
        signal: { key: 'competence', value: 'pragmatic', label: 'ROI learner', description: 'Invests in credentials with clear payoff.' },
      },
    ],
  },
  {
    id: 'q12',
    text: 'AI, robots, VR in healthcare — when you hear that, what do you actually feel?',
    probe: 'AI, robots, VR in healthcare',
    options: [
      {
        label: 'Excited. I want in on that',
        react: 'Future-facing. The emerging stuff is where you play.',
        reflect: 'the frontier tech in your field genuinely excites you',
        sections: { emerging: 3, research: 1 },
        types: { creator: 1 },
        tags: ['ai', 'robotic', 'digital', 'virtual', 'machine-learning', 'automated', 'tele', 'quantum', 'holographic'],
        signal: { key: 'openness', value: 'high', label: 'Frontier-curious', description: 'Drawn to emerging tools and new domains.' },
      },
      {
        label: 'I trust proven methods more',
        react: 'The steady hands the system runs on.',
        reflect: 'you trust what is proven over what is shiny',
        sections: { frontlineJobs: 2, government: 1 },
        types: { operator: 1 },
        signal: { key: 'openness', value: 'grounded', label: 'Proven-first', description: 'Values reliability and established practice.' },
      },
      {
        label: 'Curious but cautious',
        react: 'Healthy skepticism. The best adopters look like you.',
        reflect: 'you watch new tech closely before you commit',
        sections: { emerging: 1, industryRoles: 1 },
        signal: { key: 'openness', value: 'medium', label: 'Considered adopter', description: 'Open to the new once it earns trust.' },
      },
    ],
  },
  {
    id: 'q13',
    text: 'Almost there. Would you move abroad for work if the right door opened?',
    probe: 'move abroad for work',
    options: [
      {
        label: 'Absolutely, anywhere',
        react: 'Global ambitions. There are licensed routes for that.',
        reflect: 'you see your career on a world map, not just an India map',
        sections: { globalPathways: 3, certifications: 1 },
        tags: ['abroad', 'global', 'international', 'uk', 'usa', 'australia', 'gulf', 'nclex', 'hcpc', 'dha'],
        constraint: { key: 'geography', value: 'flexible', label: 'Open to relocating abroad' },
      },
      {
        label: 'I want to build my life in India',
        react: 'Home ground. India has more openings than people realize.',
        reflect: 'your future is here, and you are clear about that',
        sections: { government: 1, civilServices: 1 },
        constraint: { key: 'geography', value: 'india', label: 'Prefers to stay in India' },
      },
      {
        label: 'Maybe later, not right away',
        react: 'Keep the passport warm, build the base first.',
        reflect: 'you want roots first, wings later',
        sections: { globalPathways: 1 },
        constraint: { key: 'geography', value: 'later', label: 'Abroad possible later' },
      },
    ],
  },
  {
    id: 'q14',
    text: 'Money talk, just between us. If more studies made sense, how would the budget feel?',
    probe: 'how would the budget feel',
    options: [
      {
        label: 'Family can support it',
        react: 'Good. That widens the field a lot.',
        reflect: 'money will not be the thing that decides your path',
        constraint: { key: 'financial', value: 'comfortable', label: 'Can fund further study' },
      },
      {
        label: 'Tight. I need to earn while I learn',
        react: 'Then we look at earn-first paths with upgrade ramps. Plenty exist.',
        reflect: 'your plan has to pay for itself early',
        sections: { frontlineJobs: 2, certifications: 2 },
        constraint: { key: 'financial', value: 'tight', label: 'Needs early income' },
      },
      {
        label: 'Only with a scholarship or stipend',
        react: 'Funded routes exist, especially in research. Noted.',
        reflect: 'you will study more only if someone else funds it',
        sections: { research: 1, government: 1 },
        constraint: { key: 'financial', value: 'scholarship', label: 'Needs funded pathways' },
      },
    ],
  },
  {
    id: 'q15',
    text: 'Last one. When do you actually need to start earning?',
    probe: 'need to start earning',
    options: [
      {
        label: 'Basically immediately',
        react: 'Clear. We optimize for fastest solid entry.',
        reflect: 'you need income soon and your path has to respect that',
        sections: { frontlineJobs: 3, certifications: 2 },
        constraint: { key: 'timeline', value: 'immediate', label: 'Income needed within a year' },
      },
      {
        label: 'I can wait 2-3 years',
        react: 'That window fits a master s comfortably.',
        reflect: 'you can invest a couple of years before the payoff',
        sections: { pgPathways: 2 },
        constraint: { key: 'timeline', value: '2-3 years', label: 'Can invest 2-3 years first' },
      },
      {
        label: 'No pressure at all',
        react: 'Rare luxury. Use it deliberately.',
        reflect: 'you have runway, which means you can aim high',
        sections: { pgPathways: 2, research: 2, globalPathways: 1 },
        constraint: { key: 'timeline', value: 'flexible', label: 'No income pressure' },
      },
    ],
  },
];
